
################## SETUP ##################

################
# Data Sources #
################
data_sources:
    # sname is any string used as a nickname for this configuration. It will be
    ### used as the name of the folder your computed notebooks are put in
    sname: &sname
      adf-quick-run
    
    # run_dir is the path to the folder you want
    ### all the files associated with this configuration
    ### to be created in
    run_dir: .

    # nb_path_root is the path to the folder that nbscuid will
    ### look for your template notebooks in. It doesn't have to 
    ### be inside run_dir, or be specific to this project, as
    ### long as the notebooks are there
    nb_path_root: nblibrary

######################
# Computation Config #
######################

computation_config: 

    # default_kernel_name is the name of the environment that
    ### the notebooks in this configuration will be run in by default.
    ### It must already be installed on your machine. You can also
    ### specify a different environment than the default for any
    ### notebook in NOTEBOOK CONFIG

    default_kernel_name: npl-2023a


############# NOTEBOOK CONFIG #############

############################
# Notebooks and Parameters #
############################

# All parameters under global_params get passed to all the notebooks

global_params:
    test_global_param: hello

compute_notebooks:  

  # This is where all the notebooks you want run and their
  ### parameters are specified. Several examples of different
  ### types of notebooks are provided.

  # The first key (here simple_no_params_nb) is the name of the
  ### notebook from nb_path_root, minus the .ipynb
  index:
    parameter_groups:
      none:
        sname: *sname
  
  adf_quick_run:
    parameter_groups:
      none:
        sname: *sname
        adf_path: ./ADF
        config_path: .
        config_fil_str: "config_f.cam6_3_119.FLTHIST_ne30.r328_gamma0.33_soae_numcin3.001_vs_f.cam6_3_119.FLTHIST_ne30.r328_gamma0.33_soae.001.yaml"
  
  surface:
    kernel_name: mom6-tools-nbscuid
    parameter_groups:
      none:
        sname: *sname


  

  
########### JUPYTER BOOK CONFIG ###########

##################################
# Jupyter Book Table of Contents #
##################################
book_toc:
    
  # See https://jupyterbook.org/en/stable/structure/configure.html for
  ## complete documentation of Jupyter book construction options

  format: jb-book

  # All filenames are notebook filename without the .ipynb, similar to above
  
  root: index # root is the notebook that will be the homepage for the book
  parts:

    # Parts group notebooks into different sections in the Jupyter book
    ### table of contents, so you can organize different parts of your project.

    - caption: Atmosphere

      # Each chapter is the name of one of the notebooks that you executed
      ### in compute_notebooks above, also without .ipynb
      chapters:
        - file: adf_quick_run
    - caption: Ocean
      chapters:
          - file: surface


#####################################
# Keys for Jupyter Book _config.yml #
#####################################
book_config_keys:

  title: Example project   # Title of your jupyter book
  
  # Other keys can be added here, see https://jupyterbook.org/en/stable/customize/config.html
  ### for many more options
        






